-- MySQL Script generated by MySQL Workbench
-- Mon Oct 28 23:33:39 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `id` CHAR(22) NOT NULL COMMENT 'user id',
  `name` VARCHAR(64) NOT NULL COMMENT 'user name',
  `password` VARCHAR(512) NOT NULL COMMENT 'user password',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin
COMMENT = 'user table';


-- -----------------------------------------------------
-- Table `students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `students` ;

CREATE TABLE IF NOT EXISTS `students` (
  `id` CHAR(22) NOT NULL COMMENT 'user id',
  `name` VARCHAR(64) NOT NULL COMMENT 'user name',
  `phone` CHAR(11) NOT NULL COMMENT 'user phone',
  `teacher_id` CHAR(22) NOT NULL COMMENT 'teacher id',
  `class_id` CHAR(22) NOT NULL COMMENT 'class id',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin
COMMENT = 'student table';

-- -----------------------------------------------------
-- Table `teachers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teachers` ;

CREATE TABLE IF NOT EXISTS `teachers` (
  `id` CHAR(22) NOT NULL COMMENT 'teacher id',
  `name` VARCHAR(64) NOT NULL COMMENT 'teacher name',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin
COMMENT = 'teacher table';


-- -----------------------------------------------------
-- Table `classes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `classes` ;

CREATE TABLE IF NOT EXISTS `classes` (
  `id` CHAR(22) NOT NULL COMMENT 'class id',
  `name` VARCHAR(64) NOT NULL COMMENT 'class name',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin
COMMENT = 'class table';

-- -----------------------------------------------------
-- Table `courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `courses` ;

CREATE TABLE IF NOT EXISTS `courses` (
  `id` CHAR(22) NOT NULL COMMENT 'course id',
  `name` VARCHAR(64) NOT NULL COMMENT 'course name',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin
COMMENT = 'course table';

-- -----------------------------------------------------
-- Table `stu_courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stu_courses` ;

CREATE TABLE IF NOT EXISTS `stu_courses` (
  `stu_id` CHAR(22) NOT NULL COMMENT 'student id',
  `cou_id` CHAR(22) NOT NULL COMMENT 'course id',
  `score`  TINYINT NOT NULL DEFAULT 0 COMMENT 'score',
  PRIMARY KEY (`stu_id`,`cou_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin
COMMENT = 'student course table';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- Create user
-- -----------------------------------------------------
INSERT INTO `users` VALUES ('SeweQ67TDtJEPCb9yFoteL', 'tonystark', '$2b$12$/Ke/KPtY.1MOh0ZAFqa.4eueKRCMWBLLGSe4jzKYNjaBkcNPaEnay');
