version: '3.0'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql57
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "fastapi_demo"
    networks:
      fastapi_db:
        ipv4_address: 172.18.0.3
        
        

  redis:
    image: redis:5.0.0
    container_name: redisdb
    ports:
      - "26379:6379"
    networks:
      fastapi_db:
        ipv4_address: 172.18.0.4

networks:
  fastapi_db:
    ipam:
      config:
        - subnet: 172.18.0.0/16
